### ISSUE TITLE
小数点の処理について

### ISSUE THREAD

**Issue by A-B-S-I** [graycat27/FlightHUD#38]
・速度計器に関して
ぱっと見たときに、正確な速度が分かりづらい。
数値で表示するならば、小数点を削った方が良いかも？
更に、GUIの整備をするときに、
→実際の速度計器のように、ゲージを追加する
or
→数値として読みやすいように、表示の更新間隔を空ける
ので如何でしょうか。

・ピッチ角の表示について
小数点以下一桁までの表示を追加して欲しい。
エリトラで最適な飛行角度の調整をするのに、そこまでの表示があった方が良い…かもしれない。こちらは灰猫さんの判断でどうぞ。

**Comment by graycat27** [comment]
- `速度計` `高度計`の標準での小数桁数を「小数第1位まで」に変更
- `ピッチ方向(姿勢計)`も小数対応
  - 固定のゲージ（ -- 15° --）は現行のまま
  - プレイヤーの動作によって変動する表示は小数第1位まで描画

**Comment by graycat27** [comment]
![2021-03-13_11 24 00](https://user-images.githubusercontent.com/64903817/111015976-afcf8500-83ee-11eb-9520-b8df86919368.png)
- `速度計` `高度計` の桁数を減らした
描画される文字量が減ったので、もう少し描画位置を中心に寄せてもいいかもしれない。情報が視野の外側に発散してしまっている
7c01098fec2e9f7e1d6e44fb4422f53315df9e1e

**Comment by graycat27** [comment]
![2021-03-13_11 49 33](https://user-images.githubusercontent.com/64903817/111016601-3c2f7700-83f2-11eb-9e2e-e57efc50030d.png)
- `姿勢計` の桁数を増やした
fa094e56e3885d7fbbb5824a0e5ca234df10f97d
